import { subDays, subHours } from 'date-fns';
import type { Hospital, BloodInventory, UrgentRequest, DonationCamp, Donor } from './types';

export const INITIAL_HOSPITALS: Hospital[] = [
  { id: 'hosp1', name: 'D Y Patil Hospital', location: 'Nerul', address: 'D Y Patil Vidyanagar, Sector 7, Nerul, Navi Mumbai, Maharashtra 400706', lat: 19.0438, lng: 73.021, contact: '+912227735901', rating: 4.2 },
  { id: 'hosp2', name: 'Apollo Hospital', location: 'Belapur', address: 'Plot # 13, Parsik Hill Road, Off Uran Road, Sector 23, CBD Belapur, Navi Mumbai, Maharashtra 400614', lat: 19.019, lng: 73.0366, contact: '+912233503350', rating: 4.8 },
  { id: 'hosp3', name: 'MGM Hospital', location: 'Vashi', address: 'Plot No. 35, Sector 3, Vashi, Navi Mumbai, Maharashtra 400703', lat: 19.0682, lng: 73.0013, contact: '+912250666777', rating: 4.0 },
  { id: 'hosp4', name: 'Fortis Hiranandani Hospital', location: 'Vashi', address: 'Mini Sea Shore Road, Juhu Nagar, Sector 10A, Vashi, Navi Mumbai, Maharashtra 400703', lat: 19.062, lng: 72.9959, contact: '+912239199222', rating: 4.5 },
  { id: 'hosp5', name: 'Jaslok Hospital', location: 'Mumbai', address: '15, Dr. G. Deshmukh Marg, Pedder Road, Mumbai, Maharashtra 400026', lat: 18.9686, lng: 72.8087, contact: '+912261186565', rating: 4.3 },
  { id: 'hosp6', name: 'Lilavati Hospital', location: 'Mumbai', address: 'A-791, Bandra Reclamation, Bandra (W), Mumbai, Maharashtra 400050', lat: 19.053, lng: 72.829, contact: '+912226751000', rating: 4.6 },
  { id: 'hosp7', name: 'Breach Candy Hospital', location: 'Mumbai', address: '60 A, Bhulabhai Desai Road, Breach Candy, Cumballa Hill, Mumbai, Maharashtra 400026', lat: 18.9625, lng: 72.8048, contact: '+912223671888', rating: 4.7 },
  { id: 'hosp8', name: 'Kokilaben Hospital', location: 'Mumbai', address: 'Rao Saheb, Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai, Maharashtra 400053', lat: 19.1246, lng: 72.827, contact: '+912230999999', rating: 4.9 },
  { id: 'hosp9', name: 'Bombay Hospital', location: 'Mumbai', address: '12, New Marine Lines, Mumbai, Maharashtra 400020', lat: 18.942, lng: 72.826, contact: '+912222067676', rating: 4.1 },
  { id: 'hosp10', name: 'Ruby Hall Clinic', location: 'Pune', address: '40, Sasoon Rd, Sangamvadi, Pune, Maharashtra 411001', lat: 18.5316, lng: 73.8749, contact: '+912066455100', rating: 4.7 },
  { id: 'hosp11', name: 'Jehangir Hospital', location: 'Pune', address: '32, Sasoon Rd, Opposite Railway Station, Sangamvadi, Pune, Maharashtra 411001', lat: 18.5298, lng: 73.8732, contact: '+912066819999', rating: 4.4 },
  { id: 'hosp12', name: 'Sahyadri Hospital', location: 'Pune', address: 'Plot No. 30-C, Erandwane, Karve Rd, Deccan Gymkhana, Pune, Maharashtra 411004', lat: 18.5126, lng: 73.8322, contact: '+918806252525', rating: 4.6 },
  { id: 'hosp13', name: 'Deenanath Mangeshkar Hospital', location: 'Pune', address: 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra 411004', lat: 18.5042, lng: 73.834, contact: '+912040151000', rating: 4.8 },
  { id: 'hosp14', name: 'Wockhardt Hospital', location: 'Nagpur', address: '1643, North Ambazari Road, Nagpur, Maharashtra 440033', lat: 21.139, lng: 79.053, contact: '+917126624444', rating: 4.5 },
  { id: 'hosp15', name: 'Alexis Hospital', location: 'Nagpur', address: 'Mankapur, North Nagpur, Nagpur, Maharashtra 440030', lat: 21.185, lng: 79.076, contact: '+917127120000', rating: 4.3 },
  { id: 'hosp16', name: 'Orange City Hospital', location: 'Nagpur', address: '19, Khamla Rd, Swavalambi Nagar, Nagpur, Maharashtra 440022', lat: 21.115, lng: 79.055, contact: '+917122238431', rating: 4.0 },
];

export const INITIAL_INVENTORY: BloodInventory[] = [
  { id: '1', bloodType: 'A+', quantity: 25, hospitalId: 'hosp1', status: 'Available' },
  { id: '2', bloodType: 'O-', quantity: 8, hospitalId: 'hosp2', status: 'Low' },
  { id: '3', bloodType: 'B+', quantity: 3, hospitalId: 'hosp3', status: 'Critical' },
  { id: '4', bloodType: 'AB+', quantity: 15, hospitalId: 'hosp4', status: 'Available' },
  { id: '5', bloodType: 'A-', quantity: 12, hospitalId: 'hosp1', status: 'Available' },
  { id: '6', bloodType: 'O+', quantity: 50, hospitalId: 'hosp2', status: 'Available' },
  { id: '7', bloodType: 'B-', quantity: 5, hospitalId: 'hosp3', status: 'Critical' },
  { id: '8', bloodType: 'AB-', quantity: 9, hospitalId: 'hosp4', status: 'Low' },
  { id: '9', bloodType: 'A+', quantity: 30, hospitalId: 'hosp5', status: 'Available' },
  { id: '10', bloodType: 'O+', quantity: 45, hospitalId: 'hosp6', status: 'Available' },
  { id: '11', bloodType: 'B+', quantity: 18, hospitalId: 'hosp7', status: 'Available' },
  { id: '12', bloodType: 'AB-', quantity: 7, hospitalId: 'hosp8', status: 'Low' },
  { id: '13', bloodType: 'O-', quantity: 2, hospitalId: 'hosp9', status: 'Critical' },
  { id: '14', bloodType: 'A-', quantity: 22, hospitalId: 'hosp10', status: 'Available' },
  { id: '15', bloodType: 'B-', quantity: 11, hospitalId: 'hosp11', status: 'Available' },
  { id: '16', bloodType: 'AB+', quantity: 6, hospitalId: 'hosp12', status: 'Low' },
  { id: '17', bloodType: 'O+', quantity: 60, hospitalId: 'hosp13', status: 'Available' },
  { id: '18', bloodType: 'A+', quantity: 4, hospitalId: 'hosp14', status: 'Critical' },
  { id: '19', bloodType: 'B+', quantity: 20, hospitalId: 'hosp15', status: 'Available' },
  { id: '20', bloodType: 'O-', quantity: 10, hospitalId: 'hosp16', status: 'Low' },
  { id: '21', bloodType: 'A-', quantity: 14, hospitalId: 'hosp1', status: 'Available' },
  { id: '22', bloodType: 'O+', quantity: 33, hospitalId: 'hosp2', status: 'Available' },
  { id: '23', bloodType: 'B-', quantity: 1, hospitalId: 'hosp3', status: 'Critical' },
  { id: '24', bloodType: 'AB+', quantity: 19, hospitalId: 'hosp4', status: 'Available' },
  { id: '25', bloodType: 'A+', quantity: 28, hospitalId: 'hosp5', status: 'Available' },
  { id: '26', bloodType: 'O+', quantity: 40, hospitalId: 'hosp6', status: 'Available' },
  { id: '27', bloodType: 'B+', quantity: 15, hospitalId: 'hosp7', status: 'Available' },
  { id: '28', bloodType: 'AB-', quantity: 5, hospitalId: 'hosp8', status: 'Critical' },
  { id: '29', bloodType: 'O-', quantity: 9, hospitalId: 'hosp9', status: 'Low' },
  { id: '30', bloodType: 'A-', quantity: 18, hospitalId: 'hosp10', status: 'Available' },
  { id: '31', bloodType: 'B-', quantity: 13, hospitalId: 'hosp11', status: 'Available' },
  { id: '32', bloodType: 'AB+', quantity: 8, hospitalId: 'hosp12', status: 'Low' },
  { id: '33', bloodType: 'O+', quantity: 55, hospitalId: 'hosp13', status: 'Available' },
  { id: '34', bloodType: 'A+', quantity: 7, hospitalId: 'hosp14', status: 'Low' },
  { id: '35', bloodType: 'B+', quantity: 25, hospitalId: 'hosp15', status: 'Available' },
  { id: '36', bloodType: 'O-', quantity: 4, hospitalId: 'hosp16', status: 'Critical' },
  { id: '37', bloodType: 'B+', quantity: 22, hospitalId: 'hosp1', status: 'Available' },
  { id: '38', bloodType: 'AB+', quantity: 11, hospitalId: 'hosp2', status: 'Available' },
  { id: '39', bloodType: 'A-', quantity: 6, hospitalId: 'hosp3', status: 'Low' },
  { id: '40', bloodType: 'O+', quantity: 35, hospitalId: 'hosp4', status: 'Available' },
  { id: '41', bloodType: 'B-', quantity: 9, hospitalId: 'hosp5', status: 'Low' },
  { id: '42', bloodType: 'O-', quantity: 3, hospitalId: 'hosp6', status: 'Critical' },
  { id: '43', bloodType: 'A+', quantity: 40, hospitalId: 'hosp7', status: 'Available' },
  { id: '44', bloodType: 'AB-', quantity: 12, hospitalId: 'hosp8', status: 'Available' },
  { id: '45', bloodType: 'A-', quantity: 20, hospitalId: 'hosp9', status: 'Available' },
  { id: '46', bloodType: 'O+', quantity: 70, hospitalId: 'hosp10', status: 'Available' },
  { id: '47', bloodType: 'B+', quantity: 14, hospitalId: 'hosp11', status: 'Available' },
  { id: '48', bloodType: 'AB+', quantity: 4, hospitalId: 'hosp12', status: 'Critical' },
  { id: '49', bloodType: 'O-', quantity: 15, hospitalId: 'hosp13', status: 'Available' },
  { id: '50', bloodType: 'A+', quantity: 10, hospitalId: 'hosp14', status: 'Low' },
  { id: '51', bloodType: 'B-', quantity: 18, hospitalId: 'hosp15', status: 'Available' },
  { id: '52', bloodType: 'O+', quantity: 30, hospitalId: 'hosp16', status: 'Available' },
  { id: '53', bloodType: 'AB-', quantity: 2, hospitalId: 'hosp1', status: 'Critical' },
  { id: '54', bloodType: 'A+', quantity: 29, hospitalId: 'hosp2', status: 'Available' },
  { id: '55', bloodType: 'B+', quantity: 7, hospitalId: 'hosp3', status: 'Low' },
  { id: '56', bloodType: 'O-', quantity: 11, hospitalId: 'hosp4', status: 'Available' },
  { id: '57', bloodType: 'A-', quantity: 16, hospitalId: 'hosp5', status: 'Available' },
  { id: '58', bloodType: 'O+', quantity: 65, hospitalId: 'hosp6', status: 'Available' },
  { id: '59', bloodType: 'B-', quantity: 6, hospitalId: 'hosp7', status: 'Low' },
  { id: '60', bloodType: 'AB+', quantity: 10, hospitalId: 'hosp8', status: 'Low' },
  { id: '61', bloodType: 'O-', quantity: 20, hospitalId: 'hosp9', status: 'Available' },
  { id: '62', bloodType: 'A+', quantity: 32, hospitalId: 'hosp10', status: 'Available' },
  { id: '63', bloodType: 'B+', quantity: 19, hospitalId: 'hosp11', status: 'Available' },
  { id: '64', bloodType: 'AB-', quantity: 3, hospitalId: 'hosp12', status: 'Critical' },
  { id: '65', bloodType: 'O+', quantity: 48, hospitalId: 'hosp13', status: 'Available' },
  { id: '66', bloodType: 'A-', quantity: 9, hospitalId: 'hosp14', status: 'Low' },
  { id: '67', bloodType: 'B+', quantity: 28, hospitalId: 'hosp15', status: 'Available' },
  { id: '68', bloodType: 'O-', quantity: 1, hospitalId: 'hosp16', status: 'Critical' },
  { id: '69', bloodType: 'A+', quantity: 17, hospitalId: 'hosp1', status: 'Available' },
  { id: '70', bloodType: 'O+', quantity: 52, hospitalId: 'hosp2', status: 'Available' },
  { id: '71', bloodType: 'B+', quantity: 4, hospitalId: 'hosp3', status: 'Critical' },
  { id: '72', bloodType: 'AB+', quantity: 13, hospitalId: 'hosp4', status: 'Available' }
];

export const INITIAL_REQUESTS: UrgentRequest[] = [
  { id: 'req1', bloodType: 'O-', quantity: 5, urgency: 'Critical', hospitalName: 'City General Hospital', hospitalLocation: 'Mumbai', broadcastRadius: 10, createdAt: subHours(new Date(), 2).toISOString(), status: 'Active' },
  { id: 'req2', bloodType: 'A+', quantity: 10, urgency: 'High', hospitalName: 'Metro Health Center', hospitalLocation: 'Pune', broadcastRadius: 5, createdAt: subHours(new Date(), 15).toISOString(), status: 'Active' },
  { id: 'req3', bloodType: 'B+', quantity: 8, urgency: 'Moderate', hospitalName: 'Sunshine Medical', hospitalLocation: 'Nagpur', broadcastRadius: 10, createdAt: subDays(new Date(), 2).toISOString(), status: 'Fulfilled', fulfilledBy: 'Anjali Sharma' },
  { id: 'req4', bloodType: 'AB-', quantity: 3, urgency: 'Critical', hospitalName: 'Hope County Hospital', hospitalLocation: 'Mumbai', broadcastRadius: 5, createdAt: subDays(new Date(), 5).toISOString(), status: 'Expired' },
];

export const INITIAL_CAMPS: DonationCamp[] = [
  { id: 'camp1', name: 'Annual Blood Drive', organizer: 'Red Cross Society', location: 'Shivaji Park, Mumbai', address: "Shivaji Park, Dadar, Mumbai, Maharashtra 400028", lat: 19.0232, lng: 72.8421, date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(), timings: '9:00 AM - 5:00 PM' },
  { id: 'camp2', name: 'Tech Park Donation Day', organizer: 'Infosys Foundation', location: 'Hinjewadi IT Park, Pune', address: "Rajiv Gandhi Infotech Park, Hinjawadi, Pune, Maharashtra 411057", lat: 18.5842, lng: 73.7360, date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(), timings: '10:00 AM - 4:00 PM' },
  { id: 'camp3', name: 'Community Health Camp', organizer: 'Lions Club', location: 'Gandhibagh, Nagpur', address: "Gandhibagh, Nagpur, Maharashtra 440002", lat: 21.1466, lng: 79.0882, date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(), timings: '11:00 AM - 6:00 PM' },
];

export const INITIAL_DONORS: Donor[] = [
  { id: 'don1', name: 'Rohan Sharma', bloodType: 'O+', location: 'Mumbai, MH', lastDonationDate: subDays(new Date(), 90).toISOString(), contact: { phone: '+919876543210', email: 'rohan.s@example.com' } },
  { id: 'don2', name: 'Priya Mehta', bloodType: 'A+', location: 'Pune, MH', lastDonationDate: subDays(new Date(), 120).toISOString(), contact: { phone: '+919123456789', email: 'priya.m@example.com' } },
  { id: 'don3', name: 'Amit Singh', bloodType: 'B-', location: 'Nagpur, MH', lastDonationDate: subDays(new Date(), 50).toISOString(), contact: { phone: '+919988776655', email: 'amit.s@example.com' } },
  { id: 'don4', name: 'Sunita Patel', bloodType: 'AB+', location: 'Mumbai, MH', lastDonationDate: subDays(new Date(), 200).toISOString(), contact: { phone: '+919654321098', email: 'sunita.p@example.com' } },
  { id: 'don5', name: 'Vikram Reddy', bloodType: 'O-', location: 'Pune, MH', lastDonationDate: subDays(new Date(), 75).toISOString(), contact: { phone: '+919000011111', email: 'vikram.r@example.com' } },
];
