import { subDays, subHours } from 'date-fns';
import type { BloodInventory, UrgentRequest, DonationCamp, Donor } from './types';

export const INITIAL_INVENTORY: BloodInventory[] = [
  { id: '1', bloodType: 'A+', quantity: 25, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '2', bloodType: 'O-', quantity: 8, location: 'Apollo Hospital, Belapur', status: 'Low' },
  { id: '3', bloodType: 'B+', quantity: 3, location: 'MGM Hospital, Vashi', status: 'Critical' },
  { id: '4', bloodType: 'AB+', quantity: 15, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' },
  { id: '5', bloodType: 'A-', quantity: 12, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '6', bloodType: 'O+', quantity: 50, location: 'Apollo Hospital, Belapur', status: 'Available' },
  { id: '7', bloodType: 'B-', quantity: 5, location: 'MGM Hospital, Vashi', status: 'Critical' },
  { id: '8', bloodType: 'AB-', quantity: 9, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Low' },
  { id: '9', bloodType: 'A+', quantity: 30, location: 'Jaslok Hospital, Mumbai', status: 'Available' },
  { id: '10', bloodType: 'O+', quantity: 45, location: 'Lilavati Hospital, Mumbai', status: 'Available' },
  { id: '11', bloodType: 'B+', quantity: 18, location: 'Breach Candy Hospital, Mumbai', status: 'Available' },
  { id: '12', bloodType: 'AB-', quantity: 7, location: 'Kokilaben Hospital, Mumbai', status: 'Low' },
  { id: '13', bloodType: 'O-', quantity: 2, location: 'Bombay Hospital, Mumbai', status: 'Critical' },
  { id: '14', bloodType: 'A-', quantity: 22, location: 'Ruby Hall Clinic, Pune', status: 'Available' },
  { id: '15', bloodType: 'B-', quantity: 11, location: 'Jehangir Hospital, Pune', status: 'Available' },
  { id: '16', bloodType: 'AB+', quantity: 6, location: 'Sahyadri Hospital, Pune', status: 'Low' },
  { id: '17', bloodType: 'O+', quantity: 60, location: 'Deenanath Mangeshkar Hospital, Pune', status: 'Available' },
  { id: '18', bloodType: 'A+', quantity: 4, location: 'Wockhardt Hospital, Nagpur', status: 'Critical' },
  { id: '19', bloodType: 'B+', quantity: 20, location: 'Alexis Hospital, Nagpur', status: 'Available' },
  { id: '20', bloodType: 'O-', quantity: 10, location: 'Orange City Hospital, Nagpur', status: 'Low' },
  { id: '21', bloodType: 'A-', quantity: 14, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '22', bloodType: 'O+', quantity: 33, location: 'Apollo Hospital, Belapur', status: 'Available' },
  { id: '23', bloodType: 'B-', quantity: 1, location: 'MGM Hospital, Vashi', status: 'Critical' },
  { id: '24', bloodType: 'AB+', quantity: 19, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' },
  { id: '25', bloodType: 'A+', quantity: 28, location: 'Jaslok Hospital, Mumbai', status: 'Available' },
  { id: '26', bloodType: 'O+', quantity: 40, location: 'Lilavati Hospital, Mumbai', status: 'Available' },
  { id: '27', bloodType: 'B+', quantity: 15, location: 'Breach Candy Hospital, Mumbai', status: 'Available' },
  { id: '28', bloodType: 'AB-', quantity: 5, location: 'Kokilaben Hospital, Mumbai', status: 'Critical' },
  { id: '29', bloodType: 'O-', quantity: 9, location: 'Bombay Hospital, Mumbai', status: 'Low' },
  { id: '30', bloodType: 'A-', quantity: 18, location: 'Ruby Hall Clinic, Pune', status: 'Available' },
  { id: '31', bloodType: 'B-', quantity: 13, location: 'Jehangir Hospital, Pune', status: 'Available' },
  { id: '32', bloodType: 'AB+', quantity: 8, location: 'Sahyadri Hospital, Pune', status: 'Low' },
  { id: '33', bloodType: 'O+', quantity: 55, location: 'Deenanath Mangeshkar Hospital, Pune', status: 'Available' },
  { id: '34', bloodType: 'A+', quantity: 7, location: 'Wockhardt Hospital, Nagpur', status: 'Low' },
  { id: '35', bloodType: 'B+', quantity: 25, location: 'Alexis Hospital, Nagpur', status: 'Available' },
  { id: '36', bloodType: 'O-', quantity: 4, location: 'Orange City Hospital, Nagpur', status: 'Critical' },
  { id: '37', bloodType: 'B+', quantity: 22, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '38', bloodType: 'AB+', quantity: 11, location: 'Apollo Hospital, Belapur', status: 'Available' },
  { id: '39', bloodType: 'A-', quantity: 6, location: 'MGM Hospital, Vashi', status: 'Low' },
  { id: '40', bloodType: 'O+', quantity: 35, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' },
  { id: '41', bloodType: 'B-', quantity: 9, location: 'Jaslok Hospital, Mumbai', status: 'Low' },
  { id: '42', bloodType: 'O-', quantity: 3, location: 'Lilavati Hospital, Mumbai', status: 'Critical' },
  { id: '43', bloodType: 'A+', quantity: 40, location: 'Breach Candy Hospital, Mumbai', status: 'Available' },
  { id: '44', bloodType: 'AB-', quantity: 12, location: 'Kokilaben Hospital, Mumbai', status: 'Available' },
  { id: '45', bloodType: 'A-', quantity: 20, location: 'Bombay Hospital, Mumbai', status: 'Available' },
  { id: '46', bloodType: 'O+', quantity: 70, location: 'Ruby Hall Clinic, Pune', status: 'Available' },
  { id: '47', bloodType: 'B+', quantity: 14, location: 'Jehangir Hospital, Pune', status: 'Available' },
  { id: '48', bloodType: 'AB+', quantity: 4, location: 'Sahyadri Hospital, Pune', status: 'Critical' },
  { id: '49', bloodType: 'O-', quantity: 15, location: 'Deenanath Mangeshkar Hospital, Pune', status: 'Available' },
  { id: '50', bloodType: 'A+', quantity: 10, location: 'Wockhardt Hospital, Nagpur', status: 'Low' },
  { id: '51', bloodType: 'B-', quantity: 18, location: 'Alexis Hospital, Nagpur', status: 'Available' },
  { id: '52', bloodType: 'O+', quantity: 30, location: 'Orange City Hospital, Nagpur', status: 'Available' },
  { id: '53', bloodType: 'AB-', quantity: 2, location: 'D Y Patil Hospital, Nerul', status: 'Critical' },
  { id: '54', bloodType: 'A+', quantity: 29, location: 'Apollo Hospital, Belapur', status: 'Available' },
  { id: '55', bloodType: 'B+', quantity: 7, location: 'MGM Hospital, Vashi', status: 'Low' },
  { id: '56', bloodType: 'O-', quantity: 11, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' },
  { id: '57', bloodType: 'A-', quantity: 16, location: 'Jaslok Hospital, Mumbai', status: 'Available' },
  { id: '58', bloodType: 'O+', quantity: 65, location: 'Lilavati Hospital, Mumbai', status: 'Available' },
  { id: '59', bloodType: 'B-', quantity: 6, location: 'Breach Candy Hospital, Mumbai', status: 'Low' },
  { id: '60', bloodType: 'AB+', quantity: 10, location: 'Kokilaben Hospital, Mumbai', status: 'Low' },
  { id: '61', bloodType: 'O-', quantity: 20, location: 'Bombay Hospital, Mumbai', status: 'Available' },
  { id: '62', bloodType: 'A+', quantity: 32, location: 'Ruby Hall Clinic, Pune', status: 'Available' },
  { id: '63', bloodType: 'B+', quantity: 19, location: 'Jehangir Hospital, Pune', status: 'Available' },
  { id: '64', bloodType: 'AB-', quantity: 3, location: 'Sahyadri Hospital, Pune', status: 'Critical' },
  { id: '65', bloodType: 'O+', quantity: 48, location: 'Deenanath Mangeshkar Hospital, Pune', status: 'Available' },
  { id: '66', bloodType: 'A-', quantity: 9, location: 'Wockhardt Hospital, Nagpur', status: 'Low' },
  { id: '67', bloodType: 'B+', quantity: 28, location: 'Alexis Hospital, Nagpur', status: 'Available' },
  { id: '68', bloodType: 'O-', quantity: 1, location: 'Orange City Hospital, Nagpur', status: 'Critical' },
  { id: '69', bloodType: 'A+', quantity: 17, location: 'D Y Patil Hospital, Nerul', status: 'Available' },
  { id: '70', bloodType: 'O+', quantity: 52, location: 'Apollo Hospital, Belapur', status: 'Available' },
  { id: '71', bloodType: 'B+', quantity: 4, location: 'MGM Hospital, Vashi', status: 'Critical' },
  { id: '72', bloodType: 'AB+', quantity: 13, location: 'Fortis Hiranandani Hospital, Vashi', status: 'Available' }
];

export const INITIAL_REQUESTS: UrgentRequest[] = [
  { id: 'req1', bloodType: 'O-', quantity: 5, urgency: 'Critical', hospitalName: 'City General Hospital', hospitalLocation: 'Mumbai', broadcastRadius: 10, createdAt: subHours(new Date(), 2).toISOString(), status: 'Active' },
  { id: 'req2', bloodType: 'A+', quantity: 10, urgency: 'High', hospitalName: 'Metro Health Center', hospitalLocation: 'Pune', broadcastRadius: 5, createdAt: subHours(new Date(), 15).toISOString(), status: 'Active' },
  { id: 'req3', bloodType: 'B+', quantity: 8, urgency: 'Moderate', hospitalName: 'Sunshine Medical', hospitalLocation: 'Nagpur', broadcastRadius: 10, createdAt: subDays(new Date(), 2).toISOString(), status: 'Fulfilled', fulfilledBy: 'Anjali Sharma' },
  { id: 'req4', bloodType: 'AB-', quantity: 3, urgency: 'Critical', hospitalName: 'Hope County Hospital', hospitalLocation: 'Mumbai', broadcastRadius: 5, createdAt: subDays(new Date(), 5).toISOString(), status: 'Expired' },
];

export const INITIAL_CAMPS: DonationCamp[] = [
  { id: 'camp1', name: 'Annual Blood Drive', organizer: 'Red Cross Society', location: 'Shivaji Park, Mumbai', address: "Shivaji Park, Dadar, Mumbai, Maharashtra 400028", lat: 19.0232, lng: 72.8421, date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(), timings: '9:00 AM - 5:00 PM' },
  { id: 'camp2', name: 'Tech Park Donation Day', organizer: 'Infosys Foundation', location: 'Hinjewadi IT Park, Pune', address: "Rajiv Gandhi Infotech Park, Hinjawadi, Pune, Maharashtra 411057", lat: 18.5842, lng: 73.7360, date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(), timings: '10:00 AM - 4:00 PM' },
  { id: 'camp3', name: 'Community Health Camp', organizer: 'Lions Club', location: 'Gandhibagh, Nagpur', address: "Gandhibagh, Nagpur, Maharashtra 440002", lat: 21.1466, lng: 79.0882, date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(), timings: '11:00 AM - 6:00 PM' },
];

export const INITIAL_DONORS: Donor[] = [
  { id: 'don1', name: 'Rohan Sharma', bloodType: 'O+', location: 'Mumbai, MH', lastDonationDate: subDays(new Date(), 90).toISOString(), contact: { phone: '+919876543210', email: 'rohan.s@example.com' } },
  { id: 'don2', name: 'Priya Mehta', bloodType: 'A+', location: 'Pune, MH', lastDonationDate: subDays(new Date(), 120).toISOString(), contact: { phone: '+919123456789', email: 'priya.m@example.com' } },
  { id: 'don3', name: 'Amit Singh', bloodType: 'B-', location: 'Nagpur, MH', lastDonationDate: subDays(new Date(), 50).toISOString(), contact: { phone: '+919988776655', email: 'amit.s@example.com' } },
  { id: 'don4', name: 'Sunita Patel', bloodType: 'AB+', location: 'Mumbai, MH', lastDonationDate: subDays(new Date(), 200).toISOString(), contact: { phone: '+919654321098', email: 'sunita.p@example.com' } },
  { id: 'don5', name: 'Vikram Reddy', bloodType: 'O-', location: 'Pune, MH', lastDonationDate: subDays(new Date(), 75).toISOString(), contact: { phone: '+919000011111', email: 'vikram.r@example.com' } },
];
